//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindLicenseStatus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindLicenseStatus.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש או סיסמה לא תקינים.
        /// </summary>
        internal static string LoginForm_error {
            get {
                return ResourceManager.GetString("LoginForm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמה.
        /// </summary>
        internal static string LoginForm_password {
            get {
                return ResourceManager.GetString("LoginForm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בצע.
        /// </summary>
        internal static string LoginForm_submit {
            get {
                return ResourceManager.GetString("LoginForm_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש.
        /// </summary>
        internal static string LoginForm_username {
            get {
                return ResourceManager.GetString("LoginForm_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כולם.
        /// </summary>
        internal static string Report_allusers {
            get {
                return ResourceManager.GetString("Report_allusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הבהרות.
        /// </summary>
        internal static string Report_brightness {
            get {
                return ResourceManager.GetString("Report_brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רק זמן עבודה.
        /// </summary>
        internal static string Report_cleanresults {
            get {
                return ResourceManager.GetString("Report_cleanresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תקופת הדו&quot;ח.
        /// </summary>
        internal static string Report_daterange {
            get {
                return ResourceManager.GetString("Report_daterange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג הדוח.
        /// </summary>
        internal static string Report_display {
            get {
                return ResourceManager.GetString("Report_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נמצאו.
        /// </summary>
        internal static string Report_findcars {
            get {
                return ResourceManager.GetString("Report_findcars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רדום.
        /// </summary>
        internal static string Report_idles {
            get {
                return ResourceManager.GetString("Report_idles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מגדלת.
        /// </summary>
        internal static string Report_magnifiers {
            get {
                return ResourceManager.GetString("Report_magnifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תשלילים.
        /// </summary>
        internal static string Report_negatives {
            get {
                return ResourceManager.GetString("Report_negatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יומי.
        /// </summary>
        internal static string Report_perday {
            get {
                return ResourceManager.GetString("Report_perday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שעתי.
        /// </summary>
        internal static string Report_perhour {
            get {
                return ResourceManager.GetString("Report_perhour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חודשי.
        /// </summary>
        internal static string Report_permonth {
            get {
                return ResourceManager.GetString("Report_permonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שבועי.
        /// </summary>
        internal static string Report_perweek {
            get {
                return ResourceManager.GetString("Report_perweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקראו.
        /// </summary>
        internal static string Report_readcars {
            get {
                return ResourceManager.GetString("Report_readcars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גלילות.
        /// </summary>
        internal static string Report_scrollhits {
            get {
                return ResourceManager.GetString("Report_scrollhits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחלה.
        /// </summary>
        internal static string Report_starttime {
            get {
                return ResourceManager.GetString("Report_starttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בצע.
        /// </summary>
        internal static string Report_submit {
            get {
                return ResourceManager.GetString("Report_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נציג.
        /// </summary>
        internal static string Report_users {
            get {
                return ResourceManager.GetString("Report_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדלות.
        /// </summary>
        internal static string Report_zooms {
            get {
                return ResourceManager.GetString("Report_zooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התאמות בהירות.
        /// </summary>
        internal static string StatusForm_brightnesstotal {
            get {
                return ResourceManager.GetString("StatusForm_brightnesstotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מסגרת הזמן.
        /// </summary>
        internal static string StatusForm_calculationtime {
            get {
                return ResourceManager.GetString("StatusForm_calculationtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מצא.
        /// </summary>
        internal static string StatusForm_find {
            get {
                return ResourceManager.GetString("StatusForm_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ מצא.
        /// </summary>
        internal static string StatusForm_findstotal {
            get {
                return ResourceManager.GetString("StatusForm_findstotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא פעיל.
        /// </summary>
        internal static string StatusForm_inactive {
            get {
                return ResourceManager.GetString("StatusForm_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחשב.
        /// </summary>
        internal static string StatusForm_machine {
            get {
                return ResourceManager.GetString("StatusForm_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ מגדלת.
        /// </summary>
        internal static string StatusForm_magnifierstotal {
            get {
                return ResourceManager.GetString("StatusForm_magnifierstotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נחשונים.
        /// </summary>
        internal static string StatusForm_Nachshonim {
            get {
                return ResourceManager.GetString("StatusForm_Nachshonim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נחשונים - סה&quot;כ.
        /// </summary>
        internal static string StatusForm_Nachshonim_total {
            get {
                return ResourceManager.GetString("StatusForm_Nachshonim_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ תשלילים.
        /// </summary>
        internal static string StatusForm_negativestotal {
            get {
                return ResourceManager.GetString("StatusForm_negativestotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שעה ללא פעילות.
        /// </summary>
        internal static string StatusForm_NoData {
            get {
                return ResourceManager.GetString("StatusForm_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כבוי.
        /// </summary>
        internal static string StatusForm_off {
            get {
                return ResourceManager.GetString("StatusForm_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוכניות אחרות.
        /// </summary>
        internal static string StatusForm_otherprog {
            get {
                return ResourceManager.GetString("StatusForm_otherprog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פתח תקווה.
        /// </summary>
        internal static string StatusForm_PT {
            get {
                return ResourceManager.GetString("StatusForm_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פתח תקווה - סה&quot;כ.
        /// </summary>
        internal static string StatusForm_PT_Total {
            get {
                return ResourceManager.GetString("StatusForm_PT_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קרא.
        /// </summary>
        internal static string StatusForm_read {
            get {
                return ResourceManager.GetString("StatusForm_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ קרא.
        /// </summary>
        internal static string StatusForm_readstotal {
            get {
                return ResourceManager.GetString("StatusForm_readstotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ גלילה.
        /// </summary>
        internal static string StatusForm_scroolhitstotal {
            get {
                return ResourceManager.GetString("StatusForm_scroolhitstotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ נשמרו.
        /// </summary>
        internal static string StatusForm_totalcarssaved {
            get {
                return ResourceManager.GetString("StatusForm_totalcarssaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEP סגור.
        /// </summary>
        internal static string StatusForm_vepclosed {
            get {
                return ResourceManager.GetString("StatusForm_vepclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ זום.
        /// </summary>
        internal static string StatusForm_zoomstotal {
            get {
                return ResourceManager.GetString("StatusForm_zoomstotal", resourceCulture);
            }
        }
    }
}
